# -*- coding: utf-8 -*-
"""Python Read and write to CSV.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_yLzX9BOkhDLX6sF9Lw6S4ye_jjkgvNb

# Python Read and write to CSV
"""

import pandas as pd

"""## read CSV file """

df=pd.read_csv('framingham.csv')
df.head()

"""## have a dataframe and save it into CSV file"""

data={'Name':['Ahmed','Fatma','Sara'],'Age':[11,25,22]}
data_frame=pd.DataFrame(data)
data_frame

data_frame.to_csv('data.csv')

