# -*- coding: utf-8 -*-
"""Scatterplot, bar, pie and subplots.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_yLzX9BOkhDLX6sF9Lw6S4ye_jjkgvNb

# Scatterplot, bar, pie and subplots
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import matplotlib.pyplot as plt
# % matplotlib inline

"""## scatterplot"""

x = np.linspace(0, 10, 30)
y = np.sin(x)

plt.scatter(x,y,marker='o')

 
plt.xlabel("time")
plt.ylabel("value")
plt.title("sine wave")

"""## bar plot



"""

data = {'Apple':25, 'Banana':15, 'Cherry':20, 'Mango':35}
fruits = list(data.keys())
values = list(data.values())
  
fig = plt.figure(figsize = (10, 5))

plt.bar(fruits, values, color ='green',width = 0.4)
 
plt.xlabel("Fruit name")
plt.ylabel("No. of fruits")
plt.title("number of fruits")

"""## pie chart"""

plt.pie(values,labels=fruits)

"""## subplots"""

z=np.cos(x)
plt.subplot(1, 2, 1)
plt.plot(x,y)
plt.xlabel("time")
plt.ylabel("value")
plt.title("sine wave")
plt.subplot(1, 2, 2)
plt.plot(x,z)
plt.xlabel("time")
plt.ylabel("value")
plt.title("cosine wave")