# -*- coding: utf-8 -*-
"""Tensor playground.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YAgzTkQty1Z7ACiy3huk2vc6_yFi5w88

# Tensor playground

## my first Tensor
"""

import tensorflow as tf

tf.compat.v1.disable_eager_execution()
welcome_message = tf.constant('welcome for first tensor')
sess = tf.compat.v1.Session()

out=sess.run(welcome_message)
print(out)